# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0a480b9f53ee3fe4d9d44963573bcbecc4b2e0d77a664c3b30898000c078415a1c4cc9a0aa82260b3bac6e06aea5384e1acf87f6d84cee7b5627753f7d9a760

test:
  secret_key_base: 10ddc28cc6c5ef56bece43949c1ef58e84e06fe270d1fbf82f961e08e9015391bd8c4c6eef75643992ffc0c652ba91ebd4ae7e35e48f6f1f7973710218644dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
